# -*- coding: utf-8 -*-
"""Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q59QFGcK4Qn-A92QQCX-a79Jgz5lJ0Sz
"""

def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def multiply(a, b):
    return a * b

def divide(a, b):
    if b == 0:
        return "Error: Divide by zero is not allowed"
    return a / b

def clear():
    return 0


def get_number(prompt):
    while True:
        try:
            return float(input(prompt))
        except ValueError:
            print("Invalid input! Please enter a valid number.")

def show_menu():
    print("\n----- Simple Calculator -----")
    print("1. Addition (+)")
    print("2. Subtraction (-)")
    print("3. Multiplication (×)")
    print("4. Division (÷)")
    print("5. Clear")
    print("6. Exit")


def calculator():
    result = 0

    while True:
        show_menu()
        choice = input("Choose an option (1-6): ")

        if choice == '6':
            print("Calculator Closed. Goodbye!")
            break

        elif choice == '5':
            result = clear()
            print("Calculator cleared. Result =", result)

        elif choice in ['1', '2', '3', '4']:
            num1 = get_number("Enter first number: ")
            num2 = get_number("Enter second number: ")

            if choice == '1':
                result = add(num1, num2)
            elif choice == '2':
                result = subtract(num1, num2)
            elif choice == '3':
                result = multiply(num1, num2)
            elif choice == '4':
                result = divide(num1, num2)

            print("Result:", result)

        else:
            print("Invalid choice! Please select between 1 to 6.")

calculator()